### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by sandorvasas** [hapifhir/hapi-hl7v2#24]
I can't find any binary versions of HAPI HL7v2 2.3 in the Downloads section of the website, nor I'm able to build from sources.

Could you provide a binary as well, please?

**Comment by jamesagnew** [comment]
Releases are available in the [GitHub Releases section](https://github.com/hapifhir/hapi-hl7v2/releases) and on [Maven Central](https://search.maven.org/search?q=g:ca.uhn.hapi).
