### ISSUE TITLE
OBR-21 (FillerField2) is not parsed properly.

### ISSUE THREAD

**Issue by aashish-pathak** [hapifhir/hapi-hl7v2#28]
I've a HL7 message of type `ORU_R01`,

`       String msg = "MSH|^~\\&|ULTRA_V3.1|DOR|Web Portal|Web Portal|201809261039||ORU^R01|231671052|P|2.3.1|||AL|AL|AU\r"
                + "PID||123456|123456^^^^UR~7998437^^^^ULTRAREL||FALLENI^ZANE||19450128|F|||BLD 2 31 BAIRD STREET^^CANBERRA^ACT^2600||^^^^^^0894103914\r"
                + "PV1||O|SSH^SUNSHINE ACC|||||2475619L^WONG^TRICIA^^TCPL^DR^CAROLINE SPRINGS COMM. HEALTH CENTRE^LEVEL 1, 13-15 LAKE ST^^CAROLINE SPRINGS^VIC^3023^0393619300\r"
                + "ORC|RE||14-35126352-RCF-0||R\r"
                + "OBR|1||14-35126352-RCF-0|RCF^RED CELL FOLATE (RCF)^ULTRA^DORCAM||20131212|201402241145|||SSH||||201402241754||2475619L^WONG^TRICIA^^TCPL^DR|||||CAM^false^^MBI,BFO,GHB,FES,FBE|201809261039||CH|F||^^^20131212^^R\r"
                + "OBX|1|NM|14731-4^ Red cell Folate :^LN||2455|nmol/L|> 630||||F|||201809261039|CAM";`

When I'm trying to parse this message using `ca.uhn.hl7v2.parser.Parser`, it is not able to parse `OBR-21` field properly. You see in the original message, the value at `OBR-21` is `CAM^false^^MBI,BFO,GHB,FES,FBE`. However, the parser returns only `CAM`. As being a custom field, I was hoping it will return the value as it is and should not really worry about the separator (^).
Does anyone know is this an expected behavior?

**Comment by ohr** [comment]
The `^` character is always treated as component separator even if the field is a primitive ST. It's like adding an extra field to the end of a segment, separated with a `|` field separator.
If you want reserved characters literally in an HL7 message, you have to escape them (see chapter 2.7 of the HL7 spec). A component separator is escaped as `\S\`, so your OBR-21 should read like `CAM\S\false\S\\S\MBI,BFO,GHB,FES,FBE`
