### ISSUE TITLE
HAPI TestPanel WebStart fails to launch

### ISSUE THREAD

**Issue by jmacpherson** [hapifhir/hapi-hl7v2#3]
HAPI TestPanel WebStart fails to launch. Previously working. Issue appears to have started in the past two weeks. Visiting http://hl7api.sourceforge.net/hapi-testpanel/jnlp/launch.jnlp shows a 404 response

**Comment by jamesagnew** [comment]
Currently the only working way of launching the testpanel is to use the release archives here: https://github.com/hapifhir/hapi-hl7v2/releases

If anyone wants to try and get this working that would be great. Presumably a new JNLP needs to be created?

**Comment by emirozmen07** [comment]
This is still a problem.

But installing testpanel.zip from releases still works maybe docs in web page can be updated
https://hapifhir.github.io/hapi-hl7v2/hapi-testpanel/
