### ISSUE TITLE
HAPI testpanel open file throws exception

### ISSUE THREAD

**Issue by trourance** [hapifhir/hapi-hl7v2#30]
Hi,

When I try to open a HL7 file (2.4), I get the following exception.

`14:44:15,496  INFO [AWT-EventQueue-0] Hl7V2MessageCollection:900 - About to set source message for collection`
`14:44:15,500  INFO [AWT-EventQueue-0] Hl7V2MessageCollection:277 - Found ER7 message`
`14:44:15,505  INFO [AWT-EventQueue-0] Hl7V2MessageBase:256 - About to parse message`
`14:44:15,517  INFO [AWT-EventQueue-0] VersionLogger:39 - HAPI version is: 2.1-alpha1`
`14:44:15,575  INFO [AWT-EventQueue-0] Hl7V2MessageBase:272 - Done parsing message`
`14:44:15,576  INFO [AWT-EventQueue-0] Hl7V2MessageCollection:917 - Firing message change event`
`14:44:15,577  INFO [AWT-EventQueue-0] Hl7V2MessageCollection:928 - Done setting source message for collection`
`14:44:15,653  INFO [AWT-EventQueue-0] Hl7V2MessageEditorPanel:123 - Registered syntaxKit`
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException`

$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by jamesagnew** [comment]
That's a fairly old version of the Testpanel. It would probably be worth
trying on a newer version: https://github.com/hapifhir/hapi-hl7v2/releases

Cheers,
James

**Comment by trourance** [comment]
Nice thanks.

Unfortunately, when you go on the web page (
https://hapifhir.github.io/hapi-hl7v2/hapi-testpanel/install.html), it
still points to the old sourceforge download page.

**Comment by sunziren** [comment]
thank you. New version works. and solve the old problem.
