### ISSUE TITLE
Missing items when using PopulatedVisitor

### ISSUE THREAD

**Issue by mourezwell** [hapifhir/hapi-hl7v2#33]
Hello, 
When i was working on issue #31 I also noticed that the PopulatedVisitor used in test stops too early to get all populated items, in deed when dealing with this segment 
PID|1||CIPNUM^^^CAEX^CIP^^^^EX&&ES-EX~CIPTWO||DUMAS^VICTOR HUGO|ZAPATA|19740325|1
CAEX info never visited.
Regards,

**Comment by keithboone** [comment]
I've tracked this down to an error related to unpopulated elements.  It finishes after finding the first unpopulated element.

    public final static class PopulatedVisitor<T extends MessageVisitor> extends DelegatingMessageVisitor<T> {

        PopulatedVisitor(T visitor) {
            super(visitor);
        }

        @Override
        public boolean start(Group group, Location location) throws HL7Exception {
            return !group.isEmpty() && super.start(group, location);
        }

        @Override
        public boolean end(Group group, Location location) throws HL7Exception {
//            return !group.isEmpty() && super.end(group, location);
            return group.isEmpty() || super.end(group, location);
        }

        @Override
        public boolean start(Segment segment, Location location) throws HL7Exception {
            return !segment.isEmpty() && super.start(segment, location);
        }

        @Override
        public boolean end(Segment segment, Location location) throws HL7Exception {
//            return !segment.isEmpty() && super.end(segment, location);
            return segment.isEmpty() || super.end(segment, location);
        }

        @Override
        public final boolean start(Composite type, Location location) throws HL7Exception {
            return !type.isEmpty() && super.start(type, location);
        }

        @Override
        public boolean end(Composite type, Location location) throws HL7Exception {
//            return !type.isEmpty() && super.end(type, location);
            return type.isEmpty() || super.end(type, location);
        }

        @Override
        public boolean visit(Primitive type, Location location) throws HL7Exception {
//            return !type.isEmpty() && super.visit(type, location);
            return type.isEmpty() || super.visit(type, location);
        }
 

    }

Looks to be the fix.  Essentially, on end() or visit(), returning false finishes the traversal of the internal members.  That's NOT what we want.  We want to SKIP items which are empty, not finish traversing when
we find an empty item.

**Comment by mourezwell** [comment]
Yes that's what i've done in my pull request that also fixes #31 issue
