### ISSUE TITLE
OSX Installers fail to launch

### ISSUE THREAD

**Issue by jmacpherson** [hapifhir/hapi-hl7v2#4]
OSX 10.12.5 reports:
“hapi-testpanel-2.0.1” is damaged and can’t be opened. You should eject the disk image.

This also occurs with 2.0 installer

**Comment by jamesagnew** [comment]
Currently the only working way of launching the testpanel is to use the release archives here: https://github.com/hapifhir/hapi-hl7v2/releases

If anyone wants to try and get this working that would be great.
