### ISSUE TITLE
Where is the generated source code? 

### ISSUE THREAD

**Issue by milkshakeuk** [hapifhir/hapi-hl7v2#57]
Hi I can't find the output of the source generator in the repository i.e. Generated Messages, Segments, DataTypes etc
I can see the base DataTypes is there any reason they are not in the repository?

Where can they be viewed?

**Comment by jamesagnew** [comment]
Easiest thing is to download one of the source JARs from Maven Central. Click on the downloads button here: https://search.maven.org/artifact/ca.uhn.hapi/hapi-structures-v26/2.3/jar

**Comment by milkshakeuk** [comment]
@jamesagnew I'll have a look, but is there a reason it's not in the repository?

**Comment by jamesagnew** [comment]
They are generated code, and the prevailing wisdom at the time that the
generator was written (~20 years ago) was to not check generated code into
source control. We've never changed it because it's never been worth the
effort.

sent from my phone.
