### ISSUE TITLE
unit test info

### ISSUE THREAD

**Issue by milkshakeuk** [hapifhir/hapi-hl7v2#62]
There are unit tests with names such as `test1714219`, `test17142192` in `ParserTest.java` I suspect they are old issue numbers from an old bug tracking system, but I cannot understand what they are testing because there isn't enough information in the test itself.

I was wondering if those old tickets could be viewed somewhere for context?

**Comment by jamesagnew** [comment]
Unfortunately that context may well be long gone.

Those numbers likely refer to ticket numbers on our previous host, Sourceforge (and the project is still up there just to keep as much context around as possible) at https://sourceforge.net/projects/hl7api/

However, Sourceforge itself seems to have dropped its old ticket numbering scheme so you can't look things up using those umbers as far as I can see.
