### ISSUE TITLE
Missing ADT_A04 structure in hapi-structures-v251

### ISSUE THREAD

**Issue by jonathan-clark** [hapifhir/hapi-hl7v2#9]
We are using the hapi-structures-v251 module in a testing framework we are creating and we want to create ADT_A04 messages. But it seems that there are a number of missing structures in the library including ADT_A04.

**Comment by jamesagnew** [comment]
Hi Jonathan,

This is actually deliberate, please see the following FAQ: https://hapifhir.github.io/hapi-hl7v2/hapi-faq.html#missing_messages

Cheers,
James
